export const GIF_LIST_LOADING = "GIF_LIST_LOADING";
export const GIF_LIST_RESPONSE = "GIF_LIST_RESPONSE";
export const GIF_LIST_FAILURE = "GIF_LIST_FAILURE";
export const CLEAR_GIF_LIST = "CLEAR_GIF_LIST";
export const TRENDS_LIST_LOADING = "TRENDS_LIST_LOADING";
export const TRENDS_LIST_RESPONSE = "TRENDS_LIST_RESPONSE";
export const TRENDS_LIST_FAILURE = "TRENDS_LIST_FAILURE";
